### ISSUE TITLE
Help me please !

### ISSUE THREAD

**Issue by MisterFK** [gabrigcl/sidead#1]
Hi,
This issue has no link with your repo.
I see your problem on a grapesjs issue and i wanna know if you could help me.
I try to use ChartJs in GrapesJS (create block of ChartJS) did you do that?
I didn't found anythings on this subject other of yours...

Thanks !

**Comment by gabrigcl** [comment]
Yes, I did, but this plugin is part of a private project, unfortunately I can't share it.
